services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: somethingclever
      POSTGRES_USER: bikeracks
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  bikerackserver:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
